// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(yttriumFFI)
import yttriumFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_yttrium_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_yttrium_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureYttriumInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol Logger: AnyObject, Sendable {
    
    func log(message: String) 
    
}
open class LoggerImpl: Logger, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_yttrium_fn_clone_logger(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        try! rustCall { uniffi_yttrium_fn_free_logger(handle, $0) }
    }

    

    
open func log(message: String)  {try! rustCall() {
    uniffi_yttrium_fn_method_logger_log(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(message),$0
    )
}
}
    

    
}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceLogger {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceLogger] = [UniffiVTableCallbackInterfaceLogger(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterTypeLogger.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface Logger: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterTypeLogger.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface Logger: handle missing in uniffiClone")
            }
        },
        log: { (
            uniffiHandle: UInt64,
            message: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeLogger.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.log(
                     message: try FfiConverterString.lift(message)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )]
}

private func uniffiCallbackInitLogger() {
    uniffi_yttrium_fn_init_callback_vtable_logger(UniffiCallbackInterfaceLogger.vtable)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLogger: FfiConverter {
    fileprivate static let handleMap = UniffiHandleMap<Logger>()

    typealias FfiType = UInt64
    typealias SwiftType = Logger

    public static func lift(_ handle: UInt64) throws -> Logger {
        if ((handle & 1) == 0) {
            // Rust-generated handle, construct a new class that uses the handle to implement the
            // interface
            return LoggerImpl(unsafeFromHandle: handle)
        } else {
            // Swift-generated handle, get the object from the handle map
            return try handleMap.remove(handle: handle)
        }
    }

    public static func lower(_ value: Logger) -> UInt64 {
         if let rustImpl = value as? LoggerImpl {
             // Rust-implemented object.  Clone the handle and return it
            return rustImpl.uniffiCloneHandle()
         } else {
            // Swift object, generate a new vtable handle and return that.
            return handleMap.insert(obj: value)
         }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Logger {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Logger, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLogger_lift(_ handle: UInt64) throws -> Logger {
    return try FfiConverterTypeLogger.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLogger_lower(_ value: Logger) -> UInt64 {
    return FfiConverterTypeLogger.lower(value)
}






public protocol WalletConnectPayProtocol: AnyObject, Sendable {
    
    func createPayment(referenceId: String, amountUnit: String, amountValue: String) async throws  -> CreatePaymentResponseFfi
    
}
open class WalletConnectPay: WalletConnectPayProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_yttrium_fn_clone_walletconnectpay(self.handle, $0) }
    }
public convenience init(baseUrl: String) {
    let handle =
        try! rustCall() {
    uniffi_yttrium_fn_constructor_walletconnectpay_new(
        FfiConverterString.lower(baseUrl),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        try! rustCall { uniffi_yttrium_fn_free_walletconnectpay(handle, $0) }
    }

    

    
open func createPayment(referenceId: String, amountUnit: String, amountValue: String)async throws  -> CreatePaymentResponseFfi  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_yttrium_fn_method_walletconnectpay_create_payment(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(referenceId),FfiConverterString.lower(amountUnit),FfiConverterString.lower(amountValue)
                )
            },
            pollFunc: ffi_yttrium_rust_future_poll_rust_buffer,
            completeFunc: ffi_yttrium_rust_future_complete_rust_buffer,
            freeFunc: ffi_yttrium_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeCreatePaymentResponseFfi_lift,
            errorHandler: FfiConverterTypePayError_lift
        )
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWalletConnectPay: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = WalletConnectPay

    public static func lift(_ handle: UInt64) throws -> WalletConnectPay {
        return WalletConnectPay(unsafeFromHandle: handle)
    }

    public static func lower(_ value: WalletConnectPay) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WalletConnectPay {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: WalletConnectPay, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWalletConnectPay_lift(_ handle: UInt64) throws -> WalletConnectPay {
    return try FfiConverterTypeWalletConnectPay.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWalletConnectPay_lower(_ value: WalletConnectPay) -> UInt64 {
    return FfiConverterTypeWalletConnectPay.lower(value)
}




public struct AmountFfi: Equatable, Hashable, Codable {
    public var unit: String
    public var value: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(unit: String, value: String) {
        self.unit = unit
        self.value = value
    }

    
}

#if compiler(>=6)
extension AmountFfi: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAmountFfi: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AmountFfi {
        return
            try AmountFfi(
                unit: FfiConverterString.read(from: &buf), 
                value: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: AmountFfi, into buf: inout [UInt8]) {
        FfiConverterString.write(value.unit, into: &buf)
        FfiConverterString.write(value.value, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAmountFfi_lift(_ buf: RustBuffer) throws -> AmountFfi {
    return try FfiConverterTypeAmountFfi.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAmountFfi_lower(_ value: AmountFfi) -> RustBuffer {
    return FfiConverterTypeAmountFfi.lower(value)
}


public struct CreatePaymentResponseFfi: Equatable, Hashable, Codable {
    public var paymentId: String
    public var status: String
    public var amount: AmountFfi
    public var expiresAt: Int64
    public var pollInMs: Int64
    public var gatewayUrl: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(paymentId: String, status: String, amount: AmountFfi, expiresAt: Int64, pollInMs: Int64, gatewayUrl: String) {
        self.paymentId = paymentId
        self.status = status
        self.amount = amount
        self.expiresAt = expiresAt
        self.pollInMs = pollInMs
        self.gatewayUrl = gatewayUrl
    }

    
}

#if compiler(>=6)
extension CreatePaymentResponseFfi: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCreatePaymentResponseFfi: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CreatePaymentResponseFfi {
        return
            try CreatePaymentResponseFfi(
                paymentId: FfiConverterString.read(from: &buf), 
                status: FfiConverterString.read(from: &buf), 
                amount: FfiConverterTypeAmountFfi.read(from: &buf), 
                expiresAt: FfiConverterInt64.read(from: &buf), 
                pollInMs: FfiConverterInt64.read(from: &buf), 
                gatewayUrl: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: CreatePaymentResponseFfi, into buf: inout [UInt8]) {
        FfiConverterString.write(value.paymentId, into: &buf)
        FfiConverterString.write(value.status, into: &buf)
        FfiConverterTypeAmountFfi.write(value.amount, into: &buf)
        FfiConverterInt64.write(value.expiresAt, into: &buf)
        FfiConverterInt64.write(value.pollInMs, into: &buf)
        FfiConverterString.write(value.gatewayUrl, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCreatePaymentResponseFfi_lift(_ buf: RustBuffer) throws -> CreatePaymentResponseFfi {
    return try FfiConverterTypeCreatePaymentResponseFfi.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCreatePaymentResponseFfi_lower(_ value: CreatePaymentResponseFfi) -> RustBuffer {
    return FfiConverterTypeCreatePaymentResponseFfi.lower(value)
}


public struct FfiAuthorization: Equatable, Hashable, Codable {
    /**
     * The chain ID of the authorization.
     */
    public var chainId: U256
    /**
     * The address of the authorization.
     */
    public var address: Address
    /**
     * The nonce for the authorization.
     */
    public var nonce: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The chain ID of the authorization.
         */chainId: U256, 
        /**
         * The address of the authorization.
         */address: Address, 
        /**
         * The nonce for the authorization.
         */nonce: UInt64) {
        self.chainId = chainId
        self.address = address
        self.nonce = nonce
    }

    
}

#if compiler(>=6)
extension FfiAuthorization: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiAuthorization: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiAuthorization {
        return
            try FfiAuthorization(
                chainId: FfiConverterTypeU256.read(from: &buf), 
                address: FfiConverterTypeAddress.read(from: &buf), 
                nonce: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: FfiAuthorization, into buf: inout [UInt8]) {
        FfiConverterTypeU256.write(value.chainId, into: &buf)
        FfiConverterTypeAddress.write(value.address, into: &buf)
        FfiConverterUInt64.write(value.nonce, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiAuthorization_lift(_ buf: RustBuffer) throws -> FfiAuthorization {
    return try FfiConverterTypeFfiAuthorization.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiAuthorization_lower(_ value: FfiAuthorization) -> RustBuffer {
    return FfiConverterTypeFfiAuthorization.lower(value)
}


public enum PayError: Swift.Error, Equatable, Hashable, Codable, Foundation.LocalizedError {

    
    
    case Http(String
    )
    case Api(String
    )

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension PayError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePayError: FfiConverterRustBuffer {
    typealias SwiftType = PayError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PayError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Http(
            try FfiConverterString.read(from: &buf)
            )
        case 2: return .Api(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PayError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Http(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .Api(v1):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePayError_lift(_ buf: RustBuffer) throws -> PayError {
    return try FfiConverterTypePayError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePayError_lower(_ value: PayError) -> RustBuffer {
    return FfiConverterTypePayError.lower(value)
}


public enum SolanaDeriveKeypairFromMnemonicError: Swift.Error, Equatable, Hashable, Codable, Foundation.LocalizedError {

    
    
    case DerivationPath(String
    )
    case Derive(String
    )

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension SolanaDeriveKeypairFromMnemonicError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSolanaDeriveKeypairFromMnemonicError: FfiConverterRustBuffer {
    typealias SwiftType = SolanaDeriveKeypairFromMnemonicError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SolanaDeriveKeypairFromMnemonicError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .DerivationPath(
            try FfiConverterString.read(from: &buf)
            )
        case 2: return .Derive(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SolanaDeriveKeypairFromMnemonicError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .DerivationPath(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .Derive(v1):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSolanaDeriveKeypairFromMnemonicError_lift(_ buf: RustBuffer) throws -> SolanaDeriveKeypairFromMnemonicError {
    return try FfiConverterTypeSolanaDeriveKeypairFromMnemonicError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSolanaDeriveKeypairFromMnemonicError_lower(_ value: SolanaDeriveKeypairFromMnemonicError) -> RustBuffer {
    return FfiConverterTypeSolanaDeriveKeypairFromMnemonicError.lower(value)
}


/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias Address = String

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAddress: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Address {
        return try FfiConverterString.read(from: &buf)
    }

    public static func write(_ value: Address, into buf: inout [UInt8]) {
        return FfiConverterString.write(value, into: &buf)
    }

    public static func lift(_ value: RustBuffer) throws -> Address {
        return try FfiConverterString.lift(value)
    }

    public static func lower(_ value: Address) -> RustBuffer {
        return FfiConverterString.lower(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAddress_lift(_ value: RustBuffer) throws -> Address {
    return try FfiConverterTypeAddress.lift(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAddress_lower(_ value: Address) -> RustBuffer {
    return FfiConverterTypeAddress.lower(value)
}



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias AlloyError = String

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAlloyError: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AlloyError {
        return try FfiConverterString.read(from: &buf)
    }

    public static func write(_ value: AlloyError, into buf: inout [UInt8]) {
        return FfiConverterString.write(value, into: &buf)
    }

    public static func lift(_ value: RustBuffer) throws -> AlloyError {
        return try FfiConverterString.lift(value)
    }

    public static func lower(_ value: AlloyError) -> RustBuffer {
        return FfiConverterString.lower(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAlloyError_lift(_ value: RustBuffer) throws -> AlloyError {
    return try FfiConverterTypeAlloyError.lift(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAlloyError_lower(_ value: AlloyError) -> RustBuffer {
    return FfiConverterTypeAlloyError.lower(value)
}



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias AnyhowError = String

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAnyhowError: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AnyhowError {
        return try FfiConverterString.read(from: &buf)
    }

    public static func write(_ value: AnyhowError, into buf: inout [UInt8]) {
        return FfiConverterString.write(value, into: &buf)
    }

    public static func lift(_ value: RustBuffer) throws -> AnyhowError {
        return try FfiConverterString.lift(value)
    }

    public static func lower(_ value: AnyhowError) -> RustBuffer {
        return FfiConverterString.lower(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAnyhowError_lift(_ value: RustBuffer) throws -> AnyhowError {
    return try FfiConverterTypeAnyhowError.lift(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAnyhowError_lower(_ value: AnyhowError) -> RustBuffer {
    return FfiConverterTypeAnyhowError.lower(value)
}



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias Authorization = FfiAuthorization

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAuthorization: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Authorization {
        return try FfiConverterTypeFfiAuthorization.read(from: &buf)
    }

    public static func write(_ value: Authorization, into buf: inout [UInt8]) {
        return FfiConverterTypeFfiAuthorization.write(value, into: &buf)
    }

    public static func lift(_ value: RustBuffer) throws -> Authorization {
        return try FfiConverterTypeFfiAuthorization_lift(value)
    }

    public static func lower(_ value: Authorization) -> RustBuffer {
        return FfiConverterTypeFfiAuthorization_lower(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAuthorization_lift(_ value: RustBuffer) throws -> Authorization {
    return try FfiConverterTypeAuthorization.lift(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAuthorization_lower(_ value: Authorization) -> RustBuffer {
    return FfiConverterTypeAuthorization.lower(value)
}



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias B256 = String

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeB256: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> B256 {
        return try FfiConverterString.read(from: &buf)
    }

    public static func write(_ value: B256, into buf: inout [UInt8]) {
        return FfiConverterString.write(value, into: &buf)
    }

    public static func lift(_ value: RustBuffer) throws -> B256 {
        return try FfiConverterString.lift(value)
    }

    public static func lower(_ value: B256) -> RustBuffer {
        return FfiConverterString.lower(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeB256_lift(_ value: RustBuffer) throws -> B256 {
    return try FfiConverterTypeB256.lift(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeB256_lower(_ value: B256) -> RustBuffer {
    return FfiConverterTypeB256.lower(value)
}



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias Bytes = String

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBytes: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bytes {
        return try FfiConverterString.read(from: &buf)
    }

    public static func write(_ value: Bytes, into buf: inout [UInt8]) {
        return FfiConverterString.write(value, into: &buf)
    }

    public static func lift(_ value: RustBuffer) throws -> Bytes {
        return try FfiConverterString.lift(value)
    }

    public static func lower(_ value: Bytes) -> RustBuffer {
        return FfiConverterString.lower(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBytes_lift(_ value: RustBuffer) throws -> Bytes {
    return try FfiConverterTypeBytes.lift(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBytes_lower(_ value: Bytes) -> RustBuffer {
    return FfiConverterTypeBytes.lower(value)
}



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias Eip712Domain = String

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEip712Domain: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Eip712Domain {
        return try FfiConverterString.read(from: &buf)
    }

    public static func write(_ value: Eip712Domain, into buf: inout [UInt8]) {
        return FfiConverterString.write(value, into: &buf)
    }

    public static func lift(_ value: RustBuffer) throws -> Eip712Domain {
        return try FfiConverterString.lift(value)
    }

    public static func lower(_ value: Eip712Domain) -> RustBuffer {
        return FfiConverterString.lower(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEip712Domain_lift(_ value: RustBuffer) throws -> Eip712Domain {
    return try FfiConverterTypeEip712Domain.lift(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEip712Domain_lower(_ value: Eip712Domain) -> RustBuffer {
    return FfiConverterTypeEip712Domain.lower(value)
}



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias EyreError = String

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEyreError: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EyreError {
        return try FfiConverterString.read(from: &buf)
    }

    public static func write(_ value: EyreError, into buf: inout [UInt8]) {
        return FfiConverterString.write(value, into: &buf)
    }

    public static func lift(_ value: RustBuffer) throws -> EyreError {
        return try FfiConverterString.lift(value)
    }

    public static func lower(_ value: EyreError) -> RustBuffer {
        return FfiConverterString.lower(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEyreError_lift(_ value: RustBuffer) throws -> EyreError {
    return try FfiConverterTypeEyreError.lift(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEyreError_lower(_ value: EyreError) -> RustBuffer {
    return FfiConverterTypeEyreError.lower(value)
}



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias PendingTransactionError = String

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePendingTransactionError: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PendingTransactionError {
        return try FfiConverterString.read(from: &buf)
    }

    public static func write(_ value: PendingTransactionError, into buf: inout [UInt8]) {
        return FfiConverterString.write(value, into: &buf)
    }

    public static func lift(_ value: RustBuffer) throws -> PendingTransactionError {
        return try FfiConverterString.lift(value)
    }

    public static func lower(_ value: PendingTransactionError) -> RustBuffer {
        return FfiConverterString.lower(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePendingTransactionError_lift(_ value: RustBuffer) throws -> PendingTransactionError {
    return try FfiConverterTypePendingTransactionError.lift(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePendingTransactionError_lower(_ value: PendingTransactionError) -> RustBuffer {
    return FfiConverterTypePendingTransactionError.lower(value)
}



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias PrimitiveSignature = String

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePrimitiveSignature: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PrimitiveSignature {
        return try FfiConverterString.read(from: &buf)
    }

    public static func write(_ value: PrimitiveSignature, into buf: inout [UInt8]) {
        return FfiConverterString.write(value, into: &buf)
    }

    public static func lift(_ value: RustBuffer) throws -> PrimitiveSignature {
        return try FfiConverterString.lift(value)
    }

    public static func lower(_ value: PrimitiveSignature) -> RustBuffer {
        return FfiConverterString.lower(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePrimitiveSignature_lift(_ value: RustBuffer) throws -> PrimitiveSignature {
    return try FfiConverterTypePrimitiveSignature.lift(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePrimitiveSignature_lower(_ value: PrimitiveSignature) -> RustBuffer {
    return FfiConverterTypePrimitiveSignature.lower(value)
}



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias PrivateKeySigner = String

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePrivateKeySigner: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PrivateKeySigner {
        return try FfiConverterString.read(from: &buf)
    }

    public static func write(_ value: PrivateKeySigner, into buf: inout [UInt8]) {
        return FfiConverterString.write(value, into: &buf)
    }

    public static func lift(_ value: RustBuffer) throws -> PrivateKeySigner {
        return try FfiConverterString.lift(value)
    }

    public static func lower(_ value: PrivateKeySigner) -> RustBuffer {
        return FfiConverterString.lower(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePrivateKeySigner_lift(_ value: RustBuffer) throws -> PrivateKeySigner {
    return try FfiConverterTypePrivateKeySigner.lift(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePrivateKeySigner_lower(_ value: PrivateKeySigner) -> RustBuffer {
    return FfiConverterTypePrivateKeySigner.lower(value)
}



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias ProjectId = String

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeProjectId: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ProjectId {
        return try FfiConverterString.read(from: &buf)
    }

    public static func write(_ value: ProjectId, into buf: inout [UInt8]) {
        return FfiConverterString.write(value, into: &buf)
    }

    public static func lift(_ value: RustBuffer) throws -> ProjectId {
        return try FfiConverterString.lift(value)
    }

    public static func lower(_ value: ProjectId) -> RustBuffer {
        return FfiConverterString.lower(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProjectId_lift(_ value: RustBuffer) throws -> ProjectId {
    return try FfiConverterTypeProjectId.lift(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProjectId_lower(_ value: ProjectId) -> RustBuffer {
    return FfiConverterTypeProjectId.lower(value)
}



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias ReqwestError = String

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeReqwestError: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ReqwestError {
        return try FfiConverterString.read(from: &buf)
    }

    public static func write(_ value: ReqwestError, into buf: inout [UInt8]) {
        return FfiConverterString.write(value, into: &buf)
    }

    public static func lift(_ value: RustBuffer) throws -> ReqwestError {
        return try FfiConverterString.lift(value)
    }

    public static func lower(_ value: ReqwestError) -> RustBuffer {
        return FfiConverterString.lower(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeReqwestError_lift(_ value: RustBuffer) throws -> ReqwestError {
    return try FfiConverterTypeReqwestError.lift(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeReqwestError_lower(_ value: ReqwestError) -> RustBuffer {
    return FfiConverterTypeReqwestError.lower(value)
}



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias RpcError = String

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRpcError: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RpcError {
        return try FfiConverterString.read(from: &buf)
    }

    public static func write(_ value: RpcError, into buf: inout [UInt8]) {
        return FfiConverterString.write(value, into: &buf)
    }

    public static func lift(_ value: RustBuffer) throws -> RpcError {
        return try FfiConverterString.lift(value)
    }

    public static func lower(_ value: RpcError) -> RustBuffer {
        return FfiConverterString.lower(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRpcError_lift(_ value: RustBuffer) throws -> RpcError {
    return try FfiConverterTypeRpcError.lift(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRpcError_lower(_ value: RpcError) -> RustBuffer {
    return FfiConverterTypeRpcError.lower(value)
}



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias SerdeJsonError = String

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSerdeJsonError: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SerdeJsonError {
        return try FfiConverterString.read(from: &buf)
    }

    public static func write(_ value: SerdeJsonError, into buf: inout [UInt8]) {
        return FfiConverterString.write(value, into: &buf)
    }

    public static func lift(_ value: RustBuffer) throws -> SerdeJsonError {
        return try FfiConverterString.lift(value)
    }

    public static func lower(_ value: SerdeJsonError) -> RustBuffer {
        return FfiConverterString.lower(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSerdeJsonError_lift(_ value: RustBuffer) throws -> SerdeJsonError {
    return try FfiConverterTypeSerdeJsonError.lift(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSerdeJsonError_lower(_ value: SerdeJsonError) -> RustBuffer {
    return FfiConverterTypeSerdeJsonError.lower(value)
}



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias StatusCode = UInt16

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeStatusCode: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> StatusCode {
        return try FfiConverterUInt16.read(from: &buf)
    }

    public static func write(_ value: StatusCode, into buf: inout [UInt8]) {
        return FfiConverterUInt16.write(value, into: &buf)
    }

    public static func lift(_ value: UInt16) throws -> StatusCode {
        return try FfiConverterUInt16.lift(value)
    }

    public static func lower(_ value: StatusCode) -> UInt16 {
        return FfiConverterUInt16.lower(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStatusCode_lift(_ value: UInt16) throws -> StatusCode {
    return try FfiConverterTypeStatusCode.lift(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStatusCode_lower(_ value: StatusCode) -> UInt16 {
    return FfiConverterTypeStatusCode.lower(value)
}



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias TransactionReceipt = String

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTransactionReceipt: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TransactionReceipt {
        return try FfiConverterString.read(from: &buf)
    }

    public static func write(_ value: TransactionReceipt, into buf: inout [UInt8]) {
        return FfiConverterString.write(value, into: &buf)
    }

    public static func lift(_ value: RustBuffer) throws -> TransactionReceipt {
        return try FfiConverterString.lift(value)
    }

    public static func lower(_ value: TransactionReceipt) -> RustBuffer {
        return FfiConverterString.lower(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTransactionReceipt_lift(_ value: RustBuffer) throws -> TransactionReceipt {
    return try FfiConverterTypeTransactionReceipt.lift(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTransactionReceipt_lower(_ value: TransactionReceipt) -> RustBuffer {
    return FfiConverterTypeTransactionReceipt.lower(value)
}



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias U128 = String

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeU128: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> U128 {
        return try FfiConverterString.read(from: &buf)
    }

    public static func write(_ value: U128, into buf: inout [UInt8]) {
        return FfiConverterString.write(value, into: &buf)
    }

    public static func lift(_ value: RustBuffer) throws -> U128 {
        return try FfiConverterString.lift(value)
    }

    public static func lower(_ value: U128) -> RustBuffer {
        return FfiConverterString.lower(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeU128_lift(_ value: RustBuffer) throws -> U128 {
    return try FfiConverterTypeU128.lift(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeU128_lower(_ value: U128) -> RustBuffer {
    return FfiConverterTypeU128.lower(value)
}



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias U128Primitive = String

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeU128Primitive: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> U128Primitive {
        return try FfiConverterString.read(from: &buf)
    }

    public static func write(_ value: U128Primitive, into buf: inout [UInt8]) {
        return FfiConverterString.write(value, into: &buf)
    }

    public static func lift(_ value: RustBuffer) throws -> U128Primitive {
        return try FfiConverterString.lift(value)
    }

    public static func lower(_ value: U128Primitive) -> RustBuffer {
        return FfiConverterString.lower(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeU128Primitive_lift(_ value: RustBuffer) throws -> U128Primitive {
    return try FfiConverterTypeU128Primitive.lift(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeU128Primitive_lower(_ value: U128Primitive) -> RustBuffer {
    return FfiConverterTypeU128Primitive.lower(value)
}



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias U256 = String

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeU256: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> U256 {
        return try FfiConverterString.read(from: &buf)
    }

    public static func write(_ value: U256, into buf: inout [UInt8]) {
        return FfiConverterString.write(value, into: &buf)
    }

    public static func lift(_ value: RustBuffer) throws -> U256 {
        return try FfiConverterString.lift(value)
    }

    public static func lower(_ value: U256) -> RustBuffer {
        return FfiConverterString.lower(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeU256_lift(_ value: RustBuffer) throws -> U256 {
    return try FfiConverterTypeU256.lift(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeU256_lower(_ value: U256) -> RustBuffer {
    return FfiConverterTypeU256.lower(value)
}



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias U48 = String

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeU48: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> U48 {
        return try FfiConverterString.read(from: &buf)
    }

    public static func write(_ value: U48, into buf: inout [UInt8]) {
        return FfiConverterString.write(value, into: &buf)
    }

    public static func lift(_ value: RustBuffer) throws -> U48 {
        return try FfiConverterString.lift(value)
    }

    public static func lower(_ value: U48) -> RustBuffer {
        return FfiConverterString.lower(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeU48_lift(_ value: RustBuffer) throws -> U48 {
    return try FfiConverterTypeU48.lift(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeU48_lower(_ value: U48) -> RustBuffer {
    return FfiConverterTypeU48.lower(value)
}



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias U64 = String

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeU64: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> U64 {
        return try FfiConverterString.read(from: &buf)
    }

    public static func write(_ value: U64, into buf: inout [UInt8]) {
        return FfiConverterString.write(value, into: &buf)
    }

    public static func lift(_ value: RustBuffer) throws -> U64 {
        return try FfiConverterString.lift(value)
    }

    public static func lower(_ value: U64) -> RustBuffer {
        return FfiConverterString.lower(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeU64_lift(_ value: RustBuffer) throws -> U64 {
    return try FfiConverterTypeU64.lift(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeU64_lower(_ value: U64) -> RustBuffer {
    return FfiConverterTypeU64.lower(value)
}



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias U8 = String

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeU8: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> U8 {
        return try FfiConverterString.read(from: &buf)
    }

    public static func write(_ value: U8, into buf: inout [UInt8]) {
        return FfiConverterString.write(value, into: &buf)
    }

    public static func lift(_ value: RustBuffer) throws -> U8 {
        return try FfiConverterString.lift(value)
    }

    public static func lower(_ value: U8) -> RustBuffer {
        return FfiConverterString.lower(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeU8_lift(_ value: RustBuffer) throws -> U8 {
    return try FfiConverterTypeU8.lift(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeU8_lower(_ value: U8) -> RustBuffer {
    return FfiConverterTypeU8.lower(value)
}



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias Url = String

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUrl: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Url {
        return try FfiConverterString.read(from: &buf)
    }

    public static func write(_ value: Url, into buf: inout [UInt8]) {
        return FfiConverterString.write(value, into: &buf)
    }

    public static func lift(_ value: RustBuffer) throws -> Url {
        return try FfiConverterString.lift(value)
    }

    public static func lower(_ value: Url) -> RustBuffer {
        return FfiConverterString.lower(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUrl_lift(_ value: RustBuffer) throws -> Url {
    return try FfiConverterTypeUrl.lift(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUrl_lower(_ value: Url) -> RustBuffer {
    return FfiConverterTypeUrl.lower(value)
}



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias UserOperationReceipt = String

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUserOperationReceipt: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UserOperationReceipt {
        return try FfiConverterString.read(from: &buf)
    }

    public static func write(_ value: UserOperationReceipt, into buf: inout [UInt8]) {
        return FfiConverterString.write(value, into: &buf)
    }

    public static func lift(_ value: RustBuffer) throws -> UserOperationReceipt {
        return try FfiConverterString.lift(value)
    }

    public static func lower(_ value: UserOperationReceipt) -> RustBuffer {
        return FfiConverterString.lower(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUserOperationReceipt_lift(_ value: RustBuffer) throws -> UserOperationReceipt {
    return try FfiConverterTypeUserOperationReceipt.lift(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUserOperationReceipt_lower(_ value: UserOperationReceipt) -> RustBuffer {
    return FfiConverterTypeUserOperationReceipt.lower(value)
}

private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_WAKE: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureYttriumInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                { handle, pollResult in
                    uniffiFutureContinuationCallback(handle: handle, pollResult: pollResult)
                },
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}
public func registerLogger(logger: Logger)  {try! rustCall() {
    uniffi_yttrium_fn_func_register_logger(
        FfiConverterTypeLogger_lower(logger),$0
    )
}
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_yttrium_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_yttrium_checksum_func_register_logger() != 53062) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_yttrium_checksum_method_logger_log() != 540) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_yttrium_checksum_method_walletconnectpay_create_payment() != 8792) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_yttrium_checksum_constructor_walletconnectpay_new() != 14457) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitLogger()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureYttriumInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all