jdk:
  - openjdk17

android:
  components:
    - build-tools;33.0.0
    - platform-tools
    - platforms;android-33

build:
  script:
    - RELEASE_URL="https://github.com/reown-com/yttrium/releases/download/0.2.69/kotlin-artifacts.zip"
    - curl -L -o kotlin-artifacts.zip $RELEASE_URL
    - unzip kotlin-artifacts.zip -d binaries/
    - mkdir -p crates/kotlin-ffi/android/src/main/jniLibs/arm64-v8a
    - mkdir -p crates/kotlin-ffi/android/src/main/jniLibs/armeabi-v7a
    - mv binaries/yttrium/libs/arm64-v8a/libuniffi_yttrium.so crates/kotlin-ffi/android/src/main/jniLibs/arm64-v8a/
    - mv binaries/yttrium/libs/armeabi-v7a/libuniffi_yttrium.so crates/kotlin-ffi/android/src/main/jniLibs/armeabi-v7a/
    - cd crates/kotlin-ffi/android
    - ./gradlew clean --no-daemon
    - ./gradlew assembleRelease --no-daemon --refresh-dependencies --info