jdk:
  - openjdk11

android:
  components:
    - build-tools;33.0.0
    - platform-tools
    - platforms;android-33

build:
  # gradle:
  #   version: 7.4
  script:
    - cd crates/kotlin-ffi/android
    - ./gradlew clean --no-daemon
    - ./gradlew assembleRelease --no-daemon --refresh-dependencies --debug