jdk:
  - openjdk17

android:
  components:
    - build-tools;33.0.0
    - platform-tools
    - platforms;android-33

before_install:
    - RELEASE_URL="https://github.com/reown-com/yttrium/releases/download/0.2.74/kotlin-artifacts.zip"
    - echo "Fetching binaries from $RELEASE_URL"
    - curl -L -o kotlin-artifacts.zip $RELEASE_URL || echo "Failed to fetch binaries"
    - echo "Downloaded zip file:"
    - ls -l kotlin-artifacts.zip || echo "No zip file found"
    - echo "Unzipping contents..."
    - unzip kotlin-artifacts.zip -d binaries/
    - echo "Contents of binaries directory:"
    - ls -R binaries || echo "No files found in binaries directory"
    - mkdir -p crates/kotlin-ffi/android/src/main/jniLibs/arm64-v8a
    - mkdir -p crates/kotlin-ffi/android/src/main/jniLibs/armeabi-v7a
    - echo "Moving binaries..."
    - mv binaries/yttrium/libs/arm64-v8a/libuniffi_yttrium.so crates/kotlin-ffi/android/src/main/jniLibs/arm64-v8a/ || echo "Failed to move arm64-v8a .so"
    - mv binaries/yttrium/libs/armeabi-v7a/libuniffi_yttrium.so crates/kotlin-ffi/android/src/main/jniLibs/armeabi-v7a/ || echo "Failed to move armeabi-v7a .so"
    - cd crates/kotlin-ffi/android
    - ./gradlew clean --no-daemon
    - ./gradlew assembleRelease --no-daemon --refresh-dependencies --info
    - echo "Inspecting generated .aar file"
    - unzip -l build/outputs/aar/android-release.aar || echo "Failed to inspect .aar"