jdk:
  - openjdk17

android:
  components:
    - build-tools;33.0.0
    - platform-tools
    - platforms;android-33

build:
  script:
    - cd crates/kotlin-ffi
    - cargo ndk --target aarch64-linux-android build --release --features uniffi/cli
    - cargo ndk --target armv7-linux-androideabi build --release --features uniffi/cli
    - mkdir -p android/src/main/jniLibs/arm64-v8a
    - mkdir -p android/src/main/jniLibs/armeabi-v7a
    - cp ../../target/aarch64-linux-android/release/libuniffi_yttrium.so android/src/main/jniLibs/arm64-v8a/
    - cp ../../target/armv7-linux-androideabi/release/libuniffi_yttrium.so android/src/main/jniLibs/armeabi-v7a/
    - cargo run --features uniffi/cli --bin uniffi-bindgen generate \
      --library ../../target/aarch64-linux-android/release/libuniffi_yttrium.so \
      --language kotlin \
      --out-dir android/src/main/kotlin/com/reown/yttrium
    - cd android
    - ./gradlew clean --no-daemon
    - ./gradlew assembleRelease --no-daemon --refresh-dependencies --debug
    