name: dart_ffi
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter_rust_bridge: ^2.6.0
  freezed_annotation: ^2.4.4
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  freezed: ^2.5.7
  build_runner: ^2.4.13
  ffi: ^2.1.3
  ffigen: ^16.0.0
