name: dart_ffi
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

dependencies:
  flutter_rust_bridge: ^2.6.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  build_runner: ^2.4.13
  ffigen: ^16.0.0
