name: dart_ffi
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  flutter_rust_bridge: 1.82.6

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
