name: Publish Swift Utils Release

on:
  pull_request:
    types:
      - closed

env:
  PR_LABEL: swift-utils-release

permissions:
  contents: write
  pull-requests: read

jobs:
  publish-swift-utils:
    if: >-
      github.event.pull_request.merged == true &&
      contains(
        github.event.pull_request.labels.*.name,
        env.PR_LABEL
      )
    runs-on: macos-latest-xlarge
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Determine Release Version
        id: version
        run: |
          LABEL_PREFIX="${{ env.PR_LABEL }}="
          VERSION_LABEL=$(jq -r --arg prefix "$LABEL_PREFIX" 'first(.event.pull_request.labels[]?.name | select(startswith($prefix)))' "$GITHUB_EVENT_PATH")
          if [ -z "$VERSION_LABEL" ]; then
            echo "::error::Unable to determine version label starting with ${LABEL_PREFIX}" >&2
            exit 1
          fi
          VERSION=${VERSION_LABEL#${LABEL_PREFIX}}
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
          echo "Swift Utils release version: ${VERSION}" >> "$GITHUB_STEP_SUMMARY"

      - name: Download Release Artifacts
        uses: dawidd6/action-download-artifact@v3
        with:
          name: swift-utils-release-${{ steps.version.outputs.version }}
          path: Output/
          workflow: release-swift-utils.yml
          branch: release/swift-utils/${{ steps.version.outputs.version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Downloaded Artifacts
        run: |
          ls -lh Output/
          if [ ! -f "Output/libyttrium-utils.xcframework.zip" ]; then
            echo "::error::Missing libyttrium-utils.xcframework.zip"
            exit 1
          fi
          if [ ! -f "Output/libyttrium-utils-pod.zip" ]; then
            echo "::error::Missing libyttrium-utils-pod.zip"
            exit 1
          fi
          echo "✅ Release artifacts downloaded successfully" >> "$GITHUB_STEP_SUMMARY"

      - name: Tag Merge Commit
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          git tag -a "$VERSION" -m "Release YttriumUtils version $VERSION"
          git push origin "$VERSION"

      - name: Create Release for Utils
        id: create_release_utils
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: YttriumUtils ${{ steps.version.outputs.version }}
          draft: false
          prerelease: true

      - name: Upload Utils SPM zip to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_utils.outputs.upload_url }}
          asset_path: ./Output/libyttrium-utils.xcframework.zip
          asset_name: libyttrium-utils.xcframework.zip
          asset_content_type: application/zip

      - name: Upload Utils CocoaPods pod zip to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_utils.outputs.upload_url }}
          asset_path: ./Output/libyttrium-utils-pod.zip
          asset_name: libyttrium-utils-pod.zip
          asset_content_type: application/zip

      - name: Publish Utils CocoaPods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push YttriumUtilsWrapper.podspec --allow-warnings

