name: Publish Swift Utils Release

on:
  pull_request:
    types:
      - closed

env:
  PR_LABEL: swift-utils-release

permissions:
  contents: write
  pull-requests: read

jobs:
  publish-swift-utils:
    if: >-
      github.event.pull_request.merged == true &&
      contains(
        github.event.pull_request.labels.*.name,
        'swift-utils-release'
      )
    runs-on: macos-latest-xlarge
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Determine Release Version
        id: version
        run: |
          LABEL_PREFIX="${{ env.PR_LABEL }}="
          VERSION_LABEL=$(jq -r --arg prefix "$LABEL_PREFIX" 'first(.pull_request.labels[]?.name | select(startswith($prefix)))' "$GITHUB_EVENT_PATH")
          if [ -z "$VERSION_LABEL" ]; then
            echo "::error::Unable to determine version label starting with ${LABEL_PREFIX}" >&2
            exit 1
          fi
          VERSION=${VERSION_LABEL#${LABEL_PREFIX}}
          if [ -z "$VERSION" ]; then
            echo "::error::Version extracted from label '${VERSION_LABEL}' is empty" >&2
            exit 1
          fi
          # Validate version format (basic semver check)
          if ! echo "$VERSION" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+'; then
            echo "::error::Invalid version format: ${VERSION}. Expected semver (e.g., 0.1.0)" >&2
            exit 1
          fi
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
          echo "Swift Utils release version: ${VERSION}" >> "$GITHUB_STEP_SUMMARY"

      - name: Download Release Artifacts
        uses: dawidd6/action-download-artifact@v6
        with:
          name: swift-utils-release-${{ steps.version.outputs.version }}
          path: Output/
          workflow: release-swift-utils.yml
          workflow_conclusion: success
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Downloaded Artifacts
        run: |
          ls -lh Output/
          if [ ! -f "Output/libyttrium-utils.xcframework.zip" ]; then
            echo "::error::Missing libyttrium-utils.xcframework.zip"
            exit 1
          fi
          if [ ! -f "Output/libyttrium-utils-pod.zip" ]; then
            echo "::error::Missing libyttrium-utils-pod.zip"
            exit 1
          fi
          echo "✅ Release artifacts downloaded successfully" >> "$GITHUB_STEP_SUMMARY"

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: YttriumUtils ${{ steps.version.outputs.version }}
          draft: false
          prerelease: true
          files: |
            Output/libyttrium-utils.xcframework.zip
            Output/libyttrium-utils-pod.zip
          body: |
            ## YttriumUtils ${{ steps.version.outputs.version }}
            
            Swift Package Manager and CocoaPods release for Yttrium Utils.
            
            ### Installation
            
            **Swift Package Manager:**
            ```swift
            dependencies: [
                .package(url: "https://github.com/reown-com/yttrium", from: "${{ steps.version.outputs.version }}")
            ]
            ```
            
            **CocoaPods:**
            ```ruby
            pod 'YttriumUtilsWrapper', '~> ${{ steps.version.outputs.version }}'
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Utils CocoaPods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push YttriumUtilsWrapper.podspec --allow-warnings

