name: Build and Release Yttrium Swift

on:
    workflow_dispatch:
      inputs:
        version:
          description: 'Version to release (e.g. 0.0.1)'
          required: true

env:
  CARGO_TERM_COLOR: always
  VERSION: ${{ github.event.inputs.version || '0.0.24' }}
  TARGET_BRANCH: ${{ github.ref_name }}

permissions:
  contents: write  # Grant write access to repository contents for this workflow

jobs:
  release-swift-package:
    runs-on: macos-14
    strategy:
      matrix:
        config:
          - debug
    steps:
      # 1. Checkout the Repository with full history
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history so that we can create and push tags

      # 2. Setup ccache (Optional: Improve build speeds)
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.4

      # 3. Setup pnpm (JavaScript Package Manager)
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      # 4. Setup Rust Environment and Dependencies
      - name: Setup Rust Environment and Dependencies
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          rustup update stable && rustup default stable
          git submodule update --init --recursive
          make setup-thirdparty

      # 5. Select Specific Xcode Version
      - name: Select Xcode 15.4
        run: | 
          sudo xcode-select -s /Applications/Xcode_15.4.app

      # 6. Build and Package Rust XCFramework
      - name: Build and Package Rust XCFramework
        run: |
          make build-ios-bindings-release
          make zip-rust-xcframework
          make compute-rust-checksum
          make generate-package-swift

      # 7. Update Podspec with Version and Download URL
      - name: Update Podspec with Version and Download URL
        run: |
          # Replace the version line in Podspec
          sed -i '' "s/^  s\.version *= *.*/  s.version      = '${VERSION}'/g" YttriumWrapper.podspec

          # Construct the download URL
          DOWNLOAD_URL="https://github.com/reown-com/yttrium/releases/download/${VERSION}/RustXcframework.xcframework.zip"

          # Replace the download URL in prepare_command
          sed -i '' "s|curl -L -o RustXcframework.xcframework.zip '.*'|curl -L -o RustXcframework.xcframework.zip '${DOWNLOAD_URL}'|g" YttriumWrapper.podspec

      # 8. Commit and Push Package.swift and Podspec
      - name: Commit and Push Package.swift and Podspec
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use default token
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Package.swift crates/ffi/YttriumCore/Sources/YttriumCore/* YttriumWrapper.podspec
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update Package.swift and podspec for version $VERSION"
            git push origin HEAD:$TARGET_BRANCH
          fi

      # 9. Create Git Tag
      - name: Create Git Tag
        env:
          VERSION: ${{ env.VERSION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Ensure we're on the latest commit
          git fetch origin $TARGET_BRANCH
          
          # Get the latest commit hash
          COMMIT_HASH=$(git rev-parse HEAD)
          echo "Tagging commit ${COMMIT_HASH} with version ${VERSION}"
          
          # Create an annotated tag on the latest commit
          git tag -a "${VERSION}" -m "Release version ${VERSION}" "${COMMIT_HASH}"
          
          # Push the tag to the repository
          git push origin "${VERSION}"

      # 10. Create a GitHub Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Yttrium ${{ env.VERSION }}
          draft: false
          prerelease: true

      # 11. Upload Rust XCFramework to the Release
      - name: Upload Rust XCFramework to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Output/RustXcframework.xcframework.zip
          asset_name: RustXcframework.xcframework.zip
          asset_content_type: application/zip

      # 12. Publish to CocoaPods Trunk
      - name: Publish to CocoaPods Trunk
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push YttriumWrapper.podspec --allow-warnings