name: Build Yttrium Kotlin for E2E Testing
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g. 0.0.1-e2e)"
        required: false
        default: "e2e-latest"

env:
  CARGO_TERM_COLOR: always
  VERSION: ${{ github.event.inputs.version || 'e2e-latest' }}

permissions:
  contents: write

jobs:
  build-kotlin-artifacts:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-linux-android
          override: true
          components: rust-src
          
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          cmdline-tools-version: 8512546
          
      - name: Install Android NDK
        run: |
          sdkmanager --install "ndk;27.2.12479018"
          
      - name: Install cargo-ndk
        run: |
          cargo install cargo-ndk --locked
          
      - name: Build Rust library for x86_64
        run: |
          cargo ndk -t x86_64-linux-android build --profile=uniffi-release-kotlin --features=uniffi/cli
          
      - name: Generate Kotlin bindings
        run: |
          cargo run --features=uniffi/cli --bin uniffi-bindgen generate --library target/x86_64-linux-android/uniffi-release-kotlin/libuniffi_yttrium.so --language kotlin --out-dir yttrium/kotlin-bindings
          
      - name: Strip binaries
        run: |
          NDK_PATH=$ANDROID_HOME/ndk/27.2.12479018
          $NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip target/x86_64-linux-android/uniffi-release-kotlin/libuniffi_yttrium.so
          
      - name: Prepare artifacts folder
        run: |
          # Create folder structure for x86_64 Android ABI
          mkdir -p yttrium/libs/x86_64
          cp target/x86_64-linux-android/uniffi-release-kotlin/libuniffi_yttrium.so yttrium/libs/x86_64/
          
      - name: Create artifacts zip
        run: |
          zip -r kotlin-artifacts.zip yttrium/
          
      - name: Upload artifact for download
        uses: actions/upload-artifact@v4
        with:
          name: kotlin-artifacts
          path: yttrium/
          
      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: kotlin-artifacts-zip
          path: kotlin-artifacts.zip

  create-e2e-release:
    needs: build-kotlin-artifacts
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: kotlin-artifacts-zip
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: "Yttrium E2E ${{ env.VERSION }}"
          body: "Kotlin artifacts for x86_64-linux-android architecture, optimized for E2E testing on CI"
          draft: false
          prerelease: false
          
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: kotlin-artifacts.zip
          asset_name: kotlin-artifacts.zip
          asset_content_type: application/zip 